[package]
name = "graphviz"
version = "0.1.0"
authors = ["Teddy Heinen <teddy@heinen.dev>"]
edition = "2018"
description = "Safe graphviz wrapper"
build = "build.rs"

[dependencies]
graphviz-sys = { git = "https://github.com/tcheinen/graphviz-sys" }
libc = "0.2"
libloading = "0.6.2"